# Minimal config for Go library - no builds needed
builds: []

# Archives disabled for library
archives: []

# Checksums disabled for library
checksum:
  disable: true

# Changelog customization
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Release customization
release:
  github:
    owner: mfifth
    name: aisentinel-go-sdk
  draft: false
  prerelease: auto
  mode: append

# Snapshot allows building without tags
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
