# Build configuration for the CLI binary
builds:
  - main: ./cmd/aisentinel-go-sdk
    binary: aisentinel-go-sdk
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}

# Changelog customization
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Release customization
release:
  github:
    owner: mfifth
    name: aisentinel-go-sdk
  draft: false
  prerelease: auto
  mode: append

# Snapshot allows building without tags
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

